Models/Pelicula.cs
using System;
using System.ComponentModel.DataAnnotations;
using System.Data.Entity;
using System.Collections.Generic;
using System.Linq;
using System.Web;

namespace ClaseMVC.Models
{
    public enum Categoria
    {
        SciFi,
        [Display(Name = "Ciencia Ficcion")]
        Drama,
        [Display(Name = "Comedia")]
        Comedia
    }

    public class Pelicula
    {
        //public Pelicula()
        //{
        //    this.Rate = this.id = 0;
        //}

        //public int Rate { get; set; }

        public int id { get; set; }
        [Required(ErrorMessage="*")]
        [StringLength(100, MinimumLength = 5, ErrorMessage = "El {0} debe ser de al menos {2} caracteres.")]
        public string Titulo { get; set; }
        [Required(ErrorMessage = "*")]
        public string ActorPrincipal { get; set; }
               
        [DataType(DataType.Date)]
        [DisplayFormat(DataFormatString = "{0:yyyy-MM-dd}",
            ApplyFormatInEditMode = true)]
        public DateTime Fecha { get; set; }

        public decimal precio { get; set; }

        public Categoria? categoria { get; set; }

        public string ruta { get; set; }

        
    }

    public class PeliculaDBContext : DbContext
    {
        public PeliculaDBContext()
            : base("PeliculaConnection")
        {
        }

        public DbSet<Pelicula> peliculas { get; set; }
    }
}

Controllers/PeliculaController.cs
using System.Data;
using System.Data.Entity;
using System.IO;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using ClaseMVC.Models;
using PagedList;

namespace ClaseMVC.Controllers
{
    public class PeliculaController : Controller
    {
        private PeliculaDBContext db = new PeliculaDBContext();

        //
        // GET: /Pelicula/

        public ActionResult Index(int pagina = 1)
        {
            return View(db.peliculas.ToList().ToPagedList(pagina, 18));
        }


        public ActionResult rating()
        {
            return View(db.peliculas.ToList());
        }

        //
        // GET: /Pelicula/Details/5

        public ActionResult Details(int id = 0)
        {
            Pelicula pelicula = db.peliculas.Find(id);
            if (pelicula == null)
            {
                return HttpNotFound();
            }
            return View(pelicula);
        }

        //
        // GET: /Pelicula/Create
        [HttpGet]
        public ActionResult Create()
        {
            return View();
        }

        //
        // POST: /Pelicula/Create
    
        [HttpPost]
        public ActionResult Create(Pelicula pelicula, HttpPostedFileBase file)
        {
            if (ModelState.IsValid)
            {
                if (file != null && file.ContentLength > 0)
                {
                    var fileName = Path.GetFileName(file.FileName);
                    var path = Path.Combine(
                        Server.MapPath("~/Content/imagenes"),
                        fileName);
                    file.SaveAs(path);
                    //path = Url.Content(Path.Combine("~/content/imagenes", fileName));
                    path = "/content/imagenes/" + fileName;
                    pelicula.ruta = path;
                }
                db.peliculas.Add(pelicula);
                db.SaveChanges();
                return RedirectToAction("Index");
            }
            return View(pelicula);
        }

        //
        // GET: /Pelicula/Edit/5

        public ActionResult Edit(int id = 0)
        {
            Pelicula pelicula = db.peliculas.Find(id);
            if (pelicula == null)
            {
                return HttpNotFound();
            }
            return View(pelicula);
        }

        //
        // POST: /Pelicula/Edit/5
        [HttpPost]
        public ActionResult Edit(Pelicula pelicula, HttpPostedFileBase file)
        {
            if (ModelState.IsValid)
            {
                if (file != null && file.ContentLength > 0)
                {
                    var fileName = Path.GetFileName(file.FileName);
                    var path = Path.Combine(
                        Server.MapPath("~/Content/imagenes"),
                        fileName);
                    file.SaveAs(path);
                    //path = Url.Content(Path.Combine("~/content/imagenes", fileName));
                    path = "/content/imagenes/" + fileName;
                    pelicula.ruta = path;
                }
                db.Entry(pelicula).State = EntityState.Modified;
                db.SaveChanges();
                return RedirectToAction("Index");
            }
            return View(pelicula);
        }
       
        //
        // GET: /Pelicula/Delete/5

        public ActionResult Delete(int id = 0)
        {
            Pelicula pelicula = db.peliculas.Find(id);
            if (pelicula == null)
            {
                return HttpNotFound();
            }
            return View(pelicula);
        }

        //
        // POST: /Pelicula/Delete/5

        [HttpPost, ActionName("Delete")]
        public ActionResult DeleteConfirmed(int id)
        {
            Pelicula pelicula = db.peliculas.Find(id);
            db.peliculas.Remove(pelicula);
            db.SaveChanges();
            return RedirectToAction("Index");
        }

        public ActionResult RateProduct(int id, int rate)
        {
            int userId = 142; // WebSecurity.CurrentUserId;
            bool success = false;
            string error = "";

            try
            {
                success = CalificarPelicula(userId, id, rate);
            }
            catch (System.Exception ex)
            {
                // get last error
                if (ex.InnerException != null)
                    while (ex.InnerException != null)
                        ex = ex.InnerException;

                error = ex.Message;
            }

            return Json(new { error = error, success = success, pid = id }, JsonRequestBehavior.AllowGet);
        }

        public bool CalificarPelicula(int userId, int id, int calificacion)
        {
            Pelicula pelicula = db.peliculas.Find(id);
            if (pelicula == null)
            {
                return false;
            }
            //pelicula.Rate = calificacion;
            db.Entry(pelicula).State = EntityState.Modified;
            db.SaveChanges();
            return true;
        }


        protected override void Dispose(bool disposing)
        {
            db.Dispose();
            base.Dispose(disposing);
        }

        public ActionResult llamarAPI()
        {

            return View();
        }
    }
}

Views/Pelicula/Create.cshtml
@model ClaseMVC.Models.Pelicula

@{
    ViewBag.Title = "Create";
}

<h2>Create</h2>
@using (Html.BeginForm("Create", "Pelicula", FormMethod.Post, new { enctype = "multipart/form-data" }))
{
    @Html.ValidationSummary(true)

    <fieldset>
        <legend>Pelicula</legend>

        <div class="editor-label">
            @Html.LabelFor(model => model.Titulo)
        </div>
        <div class="editor-field">
            @Html.EditorFor(model => model.Titulo)
            @Html.ValidationMessageFor(model => model.Titulo)
        </div>

        <div class="editor-label">
            @Html.LabelFor(model => model.ActorPrincipal)
        </div>
        <div class="editor-field">
            @Html.EditorFor(model => model.ActorPrincipal)
            @Html.ValidationMessageFor(model => model.ActorPrincipal)
        </div>

        <div class="editor-label">
            @Html.LabelFor(model => model.Fecha)
        </div>
        <div class="editor-field">
            @Html.EditorFor(model => model.Fecha)
            @Html.ValidationMessageFor(model => model.Fecha)
        </div>
        <div class="editor-label">
            @Html.LabelFor(model => model.categoria)
        </div>
        <div class="editor-field">
            @Html.DropDownListFor(model => model.categoria,
                                  Enum.GetNames(typeof(ClaseMVC.Models.Categoria)).
                                      Select(e => new SelectListItem { Text = e }))
            @Html.ValidationMessageFor(model => model.categoria)
        </div>

        <div class="editor-label">
            Preview:
        </div>
        <div class="editor-field">
            <img id="previewImg" width="100px" height="100px" />
        </div>
        
        <div class="editor-label">
        imagen:
             </div>
            <div class="editor-field">
                <input type="file" id="file" name="file" />
            </div>
       

        <p>
            <input type="submit" value="Create" />
        </p>
    </fieldset>
}

<div>
    @Html.ActionLink("Back to List", "Index")
</div>

@section Scripts {
    @Scripts.Render("~/bundles/jqueryval")
    <script type="text/jscript">
        function readURL(input) {
            if (input.files && input.files[0]) {
                var reader = new FileReader();
                reader.onload = function (e) {
                    $('#previewImg').attr('src', e.target.result);
                }
                reader.readAsDataURL(input.files[0]);
            }
        }

        $("#file").change(function () {
            readURL(this);
        });

    </script>
}

Views/Pelicula/Delete.cshtml
@model ClaseMVC.Models.Pelicula

@{
    ViewBag.Title = "Delete";
}

<h2>Delete</h2>

<h3>Are you sure you want to delete this?</h3>
<fieldset>
    <legend>Pelicula</legend>

    <div class="display-label">
         @Html.DisplayNameFor(model => model.Titulo)
    </div>
    <div class="display-field">
        @Html.DisplayFor(model => model.Titulo)
    </div>

    <div class="display-label">
         @Html.DisplayNameFor(model => model.ActorPrincipal)
    </div>
    <div class="display-field">
        @Html.DisplayFor(model => model.ActorPrincipal)
    </div>

    <div class="display-label">
         @Html.DisplayNameFor(model => model.Fecha)
    </div>
    <div class="display-field">
        @Html.DisplayFor(model => model.Fecha)
    </div>
</fieldset>
@using (Html.BeginForm()) {
    <p>
        <input type="submit" value="Delete" /> |
        @Html.ActionLink("Back to List", "Index")
    </p>
}

Views/Pelicula/Details.cshtml
@model ClaseMVC.Models.Pelicula

@{
    
}

<link href="@Url.Content("~/Content/rating.css")" rel="stylesheet" />

<h2>Detalles</h2>

<div>

    <hr />
    <dl class="dl-horizontal">
        <dt>
            @Html.DisplayNameFor(model => model.Titulo)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Titulo)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.ActorPrincipal)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.ActorPrincipal)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Fecha)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Fecha)
        </dd>
        <dt>
            @Html.DisplayNameFor(model => model.categoria)
        </dt>
        <dd>
            @Html.DisplayFor(model => model.categoria)
        </dd>
        <dt>Image
        </dt>

        <dd>
            @*<img src="@Html.Raw(Model.ImageURL)" />*@
            <img alt="@Model.Titulo" 
                 src="@Url.Content("~" + Model.ruta)" 
                width="100px" height="100px"/>
        </dd>


        <dt>Calificación
        </dt>
        <dd >
            @*@Html.Partial("_Rating", Model)*@
            @*@Html.DisplayFor(model => model.Rate)*@
        </dd>
    </dl>
</div>
<p>
    @Html.ActionLink("Editar", "Edit", new { id = Model.id }) |
    @Html.ActionLink("Regresar", "Index")
</p>

Views/Pelicula/Edit.cshtml
@model ClaseMVC.Models.Pelicula

@{
    ViewBag.Titulo = "Edit";
}

<h2>Edit</h2>


@using (Html.BeginForm("Edit", "Pelicula", 
    FormMethod.Post, 
    new { enctype = "multipart/form-data" }))
{
    @Html.AntiForgeryToken()
    
    <div class="form-horizontal">
        <h4>Pelicula</h4>
        <hr />
        @Html.ValidationSummary(true, "", new { @class = "text-danger" })
        @Html.HiddenFor(model => model.id)


        <div class="form-group">
            @Html.LabelFor(model => model.Titulo, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Titulo, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Titulo, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.ActorPrincipal, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.ActorPrincipal, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.ActorPrincipal, "", new { @class = "text-danger" })
            </div>
        </div>

        @*<div class="form-group">
            <label class="control-label col-md-2">Thumbnail of current image:</label>
            <div class="col-md-10">
                <img src="@Html.Raw(Model.ThumbnailURL)" />
            </div>
            <label class="control-label col-md-2" for="imageFile">New image:</label>
            <div class="col-md-10">
                <input type="file" name="imageFile" accept="image/*" class="form-control fileupload" />
            </div>
        </div>*@

        <div class="form-group">
            @Html.LabelFor(model => model.Fecha, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Fecha, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Fecha, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.categoria, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.DropDownListFor(model => model.categoria, Enum.GetNames(typeof(ClaseMVC.Models.Categoria)).Select(e => new SelectListItem { Text = e }))
                @Html.ValidationMessageFor(model => model.categoria, "", new { @class = "text-danger" })
            </div>
        </div>
        <div class="form-group">
            <div class="col-md-2">
                Preview:
                </div>
            <div class="col-md-10">
                <img id="previewImg" 
                     alt="@Model.Titulo" 
                     src="@Url.Content("~" + Model.ruta)" 
                    width="100px" height="100px"/>
                @Html.HiddenFor(model => model.ruta)
            </div>
        </div>
        
        <div class="form-group">
             <div class="col-md-2">
                 imagen:
                 </div>
            <div class="col-md-10">
                
                 <input type="file" id="file" name="file" />

            </div>
        </div>
        
        <div class="form-group">
            <div class="col-md-offset-2 col-md-10">
                </div>
                <div class="col-md-10">
                    @Html.Partial("_Rating", Model)
                    @Html.HiddenFor(m=>m.Rate,new{id="Rate"})
                </div>
            </div>

        <div class="form-group">
            <div class="col-md-offset-2 col-md-10">
                <input type="submit" value="Save" class="btn btn-default" />
            </div>
        </div>
    </div>
}

<div>
    @*@Html.ActionLink("Back to List", "Index")*@
</div>



@section Scripts {
    @Scripts.Render("~/bundles/jqueryval")
    
    <script type="text/jscript">
        function readURL(input) {
            if (input.files && input.files[0]) {
                var reader = new FileReader();
                reader.onload = function (e) {
                    $('#previewImg').attr('src', e.target.result);
                }
                reader.readAsDataURL(input.files[0]);
            }
        }

        $("#file").change(function () {
            readURL(this);
        });

    </script>
    
    <script>
        $(document).ready(function () {
            var pid = $("#Rate").val();
            $('.ratting-item[data-pid=' + pid + ']').attr('checked', 'checked');
            $('.ratting-item[data-pid=' + pid + ']').prop("checked", true);
        });
        
        $(function () {
            // codigo: https://github.com/irfan/jquery-star-rating
            $('.ratting-item').rating(function (vote, event) {
                var anchor = $(event.currentTarget),
                    pid = anchor.closest(".ratting-item").data("pid"),
                    url = '@Url.Action("RateProduct", "Pelicula")';
                $("#Rate").val(vote);
                //mensaje de espera
                $('.ratting-item[data-pid=' + pid + ']')
                    .next()
                    .text("Actualizando Calificación...");

                $.ajax({
                    url: url,
                    type: "GET",
                    data: { rate: vote, id: pid },
                    success: function (data) {

                        if (data.success) {
                            $('.ratting-item[data-pid=' + data.pid + ']')
                                .next()
                                .text("Listo! (película: " + data.pid + ")");
                        }
                        else {
                            //mostrar error
                            $('.ratting-item[data-pid=' + data.pid + ']')
                                .next()
                                .text("ocurrió un error...");
                        }
                    },
                    error: function (err) {
                        // the call thrown an error
                        $('.result').text(err);
                    },
                    complete: function () {
                        //$(".loading").hide();
                    }
                });
            });

        });
    </script>

}

Views/Pelicula/Index.cshtml
@using PagedList.Mvc
@model PagedList.IPagedList<ClaseMVC.Models.Pelicula>

@{
    ViewBag.Title = "Index";
}

<h2>Index</h2>
<p>
    @Html.ActionLink("Create New", "Create")
</p>

<div class="pager" data-otf-target="#album-list">
    @Html.PagedListPager(Model, pagina => Url.Action("Index",
                                                   new {pagina}),
                         PagedListRenderOptions.MinimalWithItemCountText)
</div>

<ul id="album-list">
    @foreach (var pel in Model)
    {
        <li>
            <a href="@Url.Action("Details", new {id=pel.id})">
                    
                <img alt="@pel.Titulo" src="@Url.Content("~" + pel.ruta)" 
                     width="100px" height="100px"/>
                    
                   
                <span>@pel.Titulo</span>
            </a>
        </li>
    }
</ul>



@*<table>
    <tr>
        <th>
            @Html.DisplayNameFor(model => model.Titulo)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.ActorPrincipal)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.Fecha)
        </th>
        <th></th>
    </tr>

@foreach (var item in Model) {
    <tr>
        <td>
            @Html.DisplayFor(modelItem => item.Titulo)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.ActorPrincipal)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.Fecha)
        </td>
        <td>
            @Html.ActionLink("Edit", "Edit", new { id=item.id }) |
            @Html.ActionLink("Details", "Details", new { id=item.id }) |
            @Html.ActionLink("Delete", "Delete", new { id=item.id })
        </td>
    </tr>
}

</table>*@

Views/Pelicula/Index2.cshtml
@model IEnumerable<ClaseMVC.Models.Pelicula>

@{
    ViewBag.Title = "Index";
}

<h2>Index</h2>

<p>
    @Html.ActionLink("Create New", "Create")
</p>

<ul id="album-list">
        @foreach (var pel in Model)
        {
            <li>
                <a href="@Url.Action("Details", new {id=pel.id})">
                    
                    <img alt="@pel.Titulo" src="@Url.Content("~" + pel.ruta)" 
                        width="100px" height="100px"/>
                    
                   
                    <span>@pel.Titulo</span>
                </a>
            </li>
        }
    </ul>

@*<table>
    <tr>
        <th>
            @Html.DisplayNameFor(model => model.Titulo)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.ActorPrincipal)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.Fecha)
        </th>
        <th></th>
    </tr>

@foreach (var item in Model) {
    <tr>
        <td>
            @Html.DisplayFor(modelItem => item.Titulo)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.ActorPrincipal)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.Fecha)
        </td>
        <td>
            @Html.ActionLink("Edit", "Edit", new { id=item.id }) |
            @Html.ActionLink("Details", "Details", new { id=item.id }) |
            @Html.ActionLink("Delete", "Delete", new { id=item.id })
        </td>
    </tr>
}

</table>*@

Views/Pelicula/LlamarAPI.cshtml
@{
    ViewBag.Title = "Llamar API JQUERY";
}

<h2>Llamar API con JQuery</h2>

<div>
    <div>
        <h1>Peliculas</h1>
        <input id="buscar" type="button" value="Buscar" />
    </div>
    <div>
        <ul id="album-list"></ul>
    </div>
</div>


@section scripts{
    <script type="text/javascript">
        $(document).ready(function () {
            $('#buscar').click(function () {
                var loc = window.location.pathname;
                //var loc = "http://localhost:55092/";
                var dir = loc.substring(0, loc.lastIndexOf('/'));
                var appdir = dir.substring(0, dir.lastIndexOf('/'));
                //var apiurl = appdir + "/api/peliculas";
                
                var apiurl = "http://localhost/webapi/api/peliculas";

                $('#album-list').empty();
                $.getJSON( apiurl, function (data) {
                    $.each(data, function (i, pelicula) {
                        
                        var html = $('<li> <img src="' +  appdir +
                            pelicula.ruta + '"width="100px" heigth="100px" alt="'
                            + pelicula.Titulo + '">' + pelicula.Titulo +'</li>');
                        $('#album-list').append(html);
                    });
                });
            });
        });
    </script>
}

Views/Pelicula/rating.cshtml
@model List<ClaseMVC.Models.Pelicula>
@{
    
}
<ul class="nav nav-tabs" id="myTab">
    <li class="active"><a href="#single">Una Pelicula</a></li>
    <li><a href="#multiple">Multiples Películas</a></li>
</ul>

<div class="tab-content">
    <div class="tab-pane active" id="single">
        <h2>Rate a product individually</h2>

        @Html.Partial("_Rating", Model.FirstOrDefault())
    </div>
    <div class="tab-pane" id="multiple">
        <h2>Rate a product list</h2>

        @foreach (var p in Model)
        { 
            @Html.Partial("_Rating", p)
        }
    </div>
</div>


<link href="@Url.Content("~/Content/rating.css")" rel="stylesheet" />


@section scripts {
    <script src="@Url.Content("~/Scripts/rating.js")"></script>
    <script>
        $(function () {
            //tabs: http://twitter.github.com/bootstrap/javascript.html#tabs 
            $('#myTab a').click(function(e) {
                e.preventDefault();
                $(this).tab('show');
            });

            // codigo: https://github.com/irfan/jquery-star-rating
            $('.ratting-item').rating(function (vote, event) {
                var anchor = $(event.currentTarget),
                    pid = anchor.closest(".ratting-item").data("pid"),
                    url = '@Url.Action("RateProduct", "Pelicula")';

                //mensaje de espera
                $('.ratting-item[data-pid=' + pid + ']')
                    .next()
                    .text("Placing your vote...");

                $.ajax({
                    url: url,
                    type: "GET",
                    data: { rate: vote, id: pid },
                    success: function (data) {

                        if (data.success) {
                            
                            $('.ratting-item[data-pid=' + data.pid + ']')
                                .next()
                                .text("Listo! (pelicula: " + data.pid + ")");
                        }
                        else {
                            //mostrar error
                            $('.ratting-item[data-pid=' + data.pid + ']')
                                .next()
                                .text("ocurrió un error...");
                        }
                    },
                    error: function (err) {
                        // the call thrown an error
                        $('.result').text(err);
                    },
                    complete: function () {
                        //$(".loading").hide();
                    }
                });
            });

        });
    </script>
}